"""adding login

Revision ID: 528ff425ad55
Revises: 8c0eb97a0513
Create Date: 2024-05-29 14:28:13.534246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528ff425ad55'
down_revision = '8c0eb97a0513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
